# -*- coding: utf-8 -*-
"""Untitled60.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1266P4R9QeLIbS6gE0vWUqrODeA_kTzo9
"""

import torch
import torchvision

print(torch.__version__)
print(torchvision.__version__)
print(torch.cuda.is_available())

if torch.cuda.is_available():
    print(torch.cuda.get_device_name(0))

import datasets
import transformers
import accelerate

print("datasets:", datasets.__version__)
print("transformers:", transformers.__version__)
print("accelerate:", accelerate.__version__)

import os

# Disable torchvision usage in Hugging Face datasets
os.environ["USE_TORCHVISION"] = "0"

import datasets

datasets.config.TORCHVISION_AVAILABLE = False

print("Torchvision disabled for datasets")

# ==========================================================
# Upload Amharic Intention Dataset
# ==========================================================

from google.colab import files
import pandas as pd

uploaded = files.upload()

file_name = list(uploaded.keys())[0]

df = pd.read_csv(file_name)

print("Dataset shape:", df.shape)

df.head()

# ==========================================================
# Dataset Information
# ==========================================================

print(df.info())

print("\nLabels:")
print(df['label'].value_counts())

print("\nSplits:")
print(df['split'].value_counts())

# ==========================================================
# Cleaning
# ==========================================================

df = df.dropna()

df['text'] = df['text'].astype(str)

df['label_id'] = df['label_id'].astype(int)

df.head()

# ==========================================================
# Split Dataset
# ==========================================================

train_df = df[df['split']=="train"]
val_df   = df[df['split']=="val"]
test_df  = df[df['split']=="test"]


print("Train:", train_df.shape)
print("Validation:", val_df.shape)
print("Test:", test_df.shape)

#Convert to HuggingFace Dataset
from datasets import Dataset


train_dataset = Dataset.from_pandas(
    train_df[['text','label_id']]
)

val_dataset = Dataset.from_pandas(
    val_df[['text','label_id']]
)

test_dataset = Dataset.from_pandas(
    test_df[['text','label_id']]
)


# Rename label column
train_dataset = train_dataset.rename_column(
    "label_id",
    "labels"
)

val_dataset = val_dataset.rename_column(
    "label_id",
    "labels"
)

test_dataset = test_dataset.rename_column(
    "label_id",
    "labels"
)


print(train_dataset)

#Load XLM-RoBERTa Tokenizer
from transformers import AutoTokenizer


model_name = "xlm-roberta-base"


tokenizer = AutoTokenizer.from_pretrained(
    model_name
)


def tokenize(batch):

    return tokenizer(
        batch["text"],
        truncation=True,
        padding=False,
        max_length=128
    )


train_dataset = train_dataset.map(
    tokenize,
    batched=True
)

val_dataset = val_dataset.map(
    tokenize,
    batched=True
)

test_dataset = test_dataset.map(
    tokenize,
    batched=True
)

''''
0 Request
1 Assertion
2 Question
3 Suggestion
4 Warning
5 Sarcasm/Irony
6 Complaint
7 Phatic
8 Promise
'''
num_labels = df['label_id'].nunique()

print("Number of classes:", num_labels)

from transformers import AutoModelForSequenceClassification


model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    num_labels=num_labels
)


model.to("cuda")

label_names = {
    0:"Request",
    1:"Assertion",
    2:"Question",
    3:"Suggestion",
    4:"Warning",
    5:"Sarcasm/Irony",
    6:"Complaint",
    7:"Phatic",
    8:"Promise"
}

'''
we are using:

PyTorch: 2.11.0+cu128
Transformers: 5.13.1
GPU: Tesla T4
'''
# ==========================================================
# Data Collator + Evaluation Metrics
# ==========================================================

from transformers import DataCollatorWithPadding
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)


data_collator = DataCollatorWithPadding(
    tokenizer=tokenizer
)


def compute_metrics(eval_pred):

    predictions, labels = eval_pred

    predictions = predictions.argmax(axis=-1)

    accuracy = accuracy_score(
        labels,
        predictions
    )

    precision = precision_score(
        labels,
        predictions,
        average="weighted",
        zero_division=0
    )

    recall = recall_score(
        labels,
        predictions,
        average="weighted",
        zero_division=0
    )

    f1 = f1_score(
        labels,
        predictions,
        average="weighted",
        zero_division=0
    )


    return {
        "accuracy": accuracy,
        "precision": precision,
        "recall": recall,
        "f1": f1
    }

# ==========================================================
# Training Configuration
# ==========================================================

from transformers import TrainingArguments


training_args = TrainingArguments(

    output_dir="./XLMR_Amharic_Intention",

    num_train_epochs=10,

    learning_rate=2e-5,

    per_device_train_batch_size=16,

    per_device_eval_batch_size=16,

    weight_decay=0.01,

    eval_strategy="epoch",

    save_strategy="epoch",

    logging_strategy="epoch",

    load_best_model_at_end=True,

    metric_for_best_model="f1",

    greater_is_better=True,

    fp16=True,

    report_to="none"
)

# ==========================================================
# Trainer (Transformers 5.x compatible)
# ==========================================================

from transformers import Trainer


trainer = Trainer(

    model=model,

    args=training_args,

    train_dataset=train_dataset,

    eval_dataset=val_dataset,

    processing_class=tokenizer,

    data_collator=data_collator,

    compute_metrics=compute_metrics
)


print("Trainer created successfully")

# ==========================================================
# Training Started
# ==========================================================

import time


start_time = time.time()


trainer.train()


training_time = time.time() - start_time


print(
    "Training completed"
)

print(
    "Training time:",
    round(training_time/60,2),
    "minutes"
)

print(train_dataset.labels[:20])

print(train_dataset.__dict__)

import numpy as np

print(np.unique(train_dataset.labels, return_counts=True))

print(df.head())

print(
    df[["label", "label_id"]]
    .drop_duplicates()
    .sort_values("label_id")
)

label2id = {
    "Request": 0,
    "Assertion": 1,
    "Refusal": 2,
    "Suggestion": 3,
    "Warning": 4,
    "Sarcasm/Irony": 5,
    "Complaint": 6,
    "Phatic": 7,
    "Promise": 8
}

def convert_labels(example):
    example["labels"] = label2id[example["labels"]]
    return example


test_dataset = test_dataset.map(
    convert_labels
)

print(test_dataset[0])

predictions = trainer.predict(test_dataset)

print(predictions)

import numpy as np
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)


# Get predicted class IDs
y_pred = np.argmax(
    predictions.predictions,
    axis=1
)


# Get true class IDs
y_true = predictions.label_ids


# Calculate metrics
xlmr_accuracy = accuracy_score(
    y_true,
    y_pred
)

xlmr_precision = precision_score(
    y_true,
    y_pred,
    average="weighted",
    zero_division=0
)

xlmr_recall = recall_score(
    y_true,
    y_pred,
    average="weighted",
    zero_division=0
)

xlmr_f1 = f1_score(
    y_true,
    y_pred,
    average="weighted",
    zero_division=0
)


print("="*60)
print("XLM-RoBERTa Test Results")
print("="*60)

print(f"Accuracy : {xlmr_accuracy:.4f}")
print(f"Precision: {xlmr_precision:.4f}")
print(f"Recall   : {xlmr_recall:.4f}")
print(f"F1-score : {xlmr_f1:.4f}")

# ==========================================================
# XLM-RoBERTa Test Evaluation
# ==========================================================

import numpy as np
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)


print("="*60)
print("Testing XLM-RoBERTa on Test Dataset")
print("="*60)


# Prediction on test dataset
predictions = trainer.predict(test_dataset)


# Convert logits to predicted labels
y_pred = np.argmax(
    predictions.predictions,
    axis=1
)


# True labels
y_true = predictions.label_ids


# ==========================================================
# Calculate Test Metrics
# ==========================================================

accuracy = accuracy_score(
    y_true,
    y_pred
)

precision = precision_score(
    y_true,
    y_pred,
    average="weighted",
    zero_division=0
)

recall = recall_score(
    y_true,
    y_pred,
    average="weighted",
    zero_division=0
)

f1 = f1_score(
    y_true,
    y_pred,
    average="weighted",
    zero_division=0
)


# ==========================================================
# Save XLM-RoBERTa Real Test Performance
# ==========================================================

xlmr_accuracy = accuracy
xlmr_precision = precision
xlmr_recall = recall
xlmr_f1 = f1


print("\nXLM-RoBERTa Test Results")
print("="*60)

print(f"Accuracy : {xlmr_accuracy:.4f}")
print(f"Precision: {xlmr_precision:.4f}")
print(f"Recall   : {xlmr_recall:.4f}")
print(f"F1-score : {xlmr_f1:.4f}")


# ==========================================================
# Classification Report
# ==========================================================

label_names = [
    "Request",
    "Assertion",
    "Refusal",
    "Suggestion",
    "Warning",
    "Sarcasm/Irony",
    "Complaint",
    "Phatic",
    "Promise"
]


print("\nClassification Report")
print("="*60)

print(
    classification_report(
        y_true,
        y_pred,
        target_names=label_names,
        zero_division=0
    )
)


# ==========================================================
# Confusion Matrix
# ==========================================================

cm = confusion_matrix(
    y_true,
    y_pred
)

print("\nConfusion Matrix")
print("="*60)

print(cm)

# Save XLM-RoBERTa real performance

xlmr_accuracy = accuracy_score(
    y_true,
    y_pred
)

xlmr_precision = precision_score(
    y_true,
    y_pred,
    average="weighted",
    zero_division=0
)

xlmr_recall = recall_score(
    y_true,
    y_pred,
    average="weighted",
    zero_division=0
)

xlmr_f1 = f1_score(
    y_true,
    y_pred,
    average="weighted",
    zero_division=0
)

print(xlmr_accuracy, xlmr_f1)

print(
    classification_report(
        y_true,
        y_pred,
        target_names=[
            "Request",
            "Assertion",
            "Refusal",
            "Suggestion",
            "Warning",
            "Sarcasm/Irony",
            "Complaint",
            "Phatic",
            "Promise"
        ],
        zero_division=0
    )
)

# ==========================================================
# XLM-RoBERTa Confusion Matrix Heatmap
# ==========================================================

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix


# Correct label order from your dataset
label_names = [
    "Request",
    "Assertion",
    "Refusal",
    "Suggestion",
    "Warning",
    "Sarcasm/Irony",
    "Complaint",
    "Phatic",
    "Promise"
]


# Generate confusion matrix
cm = confusion_matrix(
    y_true,
    y_pred
)


# Plot heatmap
plt.figure(figsize=(10, 8))

sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues",
    xticklabels=label_names,
    yticklabels=label_names
)


plt.xlabel("Predicted Label")
plt.ylabel("True Label")

plt.title(
    "Confusion Matrix of XLM-RoBERTa for Amharic Intention Detection"
)


plt.xticks(
    rotation=45,
    ha="right"
)

plt.yticks(
    rotation=0
)

plt.tight_layout()

plt.show()

import os

os.environ["TRANSFORMERS_NO_TORCHVISION"] = "1"
os.environ["DATASETS_DISABLE_TORCHVISION"] = "1"

test_dataset.set_format(
    type="torch",
    columns=[
        "input_ids",
        "attention_mask",
        "labels"
    ]
)

print(test_dataset.column_names)

import torch
import torchvision

print("PyTorch:", torch.__version__)
print("Torchvision:", torchvision.__version__)

# ==========================================================
# Cell 13: Confusion Matrix Plot
# ==========================================================

import matplotlib.pyplot as plt
import seaborn as sns


plt.figure(figsize=(10,8))

sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues",
    xticklabels=label_names,
    yticklabels=label_names
)


plt.xlabel("Predicted Label")
plt.ylabel("True Label")
plt.title("Confusion Matrix - XLM-RoBERTa Amharic Intention Detection")

plt.xticks(
    rotation=45,
    ha="right"
)

plt.yticks(
    rotation=0
)

plt.tight_layout()

plt.show()

# ==========================================================
# Cell 14: Per-Class F1 Score
# ==========================================================

from sklearn.metrics import f1_score
import pandas as pd
import matplotlib.pyplot as plt


class_f1 = f1_score(
    y_true,
    y_pred,
    average=None
)


f1_df = pd.DataFrame({

    "Intent": label_names,

    "F1-score": class_f1

})


print(f1_df)


plt.figure(figsize=(10,5))

plt.bar(
    f1_df["Intent"],
    f1_df["F1-score"]
)


plt.xlabel("Intent Class")

plt.ylabel("F1-score")

plt.title(
    "Per-Class F1-score of XLM-RoBERTa"
)


plt.xticks(
    rotation=45,
    ha="right"
)

plt.ylim(0,1)

plt.tight_layout()

plt.show()

# ==========================================================
# Cell 15: Save Classification Results
# ==========================================================

report = classification_report(
    y_true,
    y_pred,
    target_names=label_names,
    output_dict=True,
    zero_division=0
)


report_df = pd.DataFrame(report).transpose()


report_df.to_csv(
    "XLMR_classification_report.csv"
)


print(
    "Classification report saved successfully"
)


report_df

# ==========================================================
# Cell 16: Save Trained XLM-RoBERTa Model
# ==========================================================


model_path = "./XLMR_Amharic_Intention_Model"


trainer.save_model(
    model_path
)


tokenizer.save_pretrained(
    model_path
)


print(
    "Model saved at:",
    model_path
)

# ==========================================================
# Cell 18: Final Performance Table
# ==========================================================

results_table = pd.DataFrame({

    "Model": [
        "XLM-RoBERTa"
    ],

    "Accuracy": [
        accuracy
    ],

    "Precision": [
        precision
    ],

    "Recall": [
        recall
    ],

    "F1-score": [
        f1
    ],

    "Training Time (minutes)": [
        training_time / 60
    ]

})


results_table

results_table.to_csv(
    "XLMR_final_results.csv",
    index=False
)

print("Results exported successfully")

#Load AfroXLM-R Tokenizer
# ==========================================================
# AfroXLM-R Tokenizer
# ==========================================================

from transformers import AutoTokenizer

afro_model_name = "Davlan/afro-xlmr-base"

afro_tokenizer = AutoTokenizer.from_pretrained(
    afro_model_name
)

print("AfroXLM-R tokenizer loaded successfully")

# ==========================================================
# AfroXLM-R Tokenization
# ==========================================================

def afro_tokenize(batch):

    return afro_tokenizer(
        batch["text"],
        truncation=True,
        max_length=128
    )


afro_train_dataset = train_dataset.map(
    afro_tokenize,
    batched=True
)

afro_val_dataset = val_dataset.map(
    afro_tokenize,
    batched=True
)

afro_test_dataset = test_dataset.map(
    afro_tokenize,
    batched=True
)


print(afro_train_dataset)

import torch

print(torch.__version__)
print(torch.cuda.is_available())

if torch.cuda.is_available():
    print(torch.cuda.get_device_name(0))

# ==========================================================
# Load AfroXLM-R Classification Model
# ==========================================================

from transformers import AutoModelForSequenceClassification


afro_model = AutoModelForSequenceClassification.from_pretrained(
    afro_model_name,
    num_labels=num_labels
)


afro_model.to("cuda")


print("AfroXLM-R model loaded")

#Create AfroXLM-R Trainer
# ==========================================================
# AfroXLM-R Trainer
# ==========================================================

from transformers import Trainer


afro_trainer = Trainer(

    model=afro_model,

    args=training_args,

    train_dataset=afro_train_dataset,

    eval_dataset=afro_val_dataset,

    processing_class=afro_tokenizer,

    data_collator=data_collator,

    compute_metrics=compute_metrics
)


print("AfroXLM-R Trainer created")

#Train AfroXLM-R
# ==========================================================
# AfroXLM-R Training
# ==========================================================

import time


afro_start_time = time.time()


afro_trainer.train()


afro_training_time = time.time() - afro_start_time


print(
    "Training time:",
    round(afro_training_time/60,2),
    "minutes"
)

#Evaluate AfroXLM-R
# ==========================================================
# AfroXLM-R Test Evaluation
# ==========================================================

afro_test_results = afro_trainer.evaluate(
    afro_test_dataset
)


afro_test_results

afro_test_results

# ==========================================================
# Save AfroXLM-R Results
# ==========================================================

afro_results = {
    "Model": "AfroXLM-R",
    "Accuracy": 79.86,
    "Precision": 85.10,
    "Recall": 79.86,
    "F1-score": 78.22
}

print(afro_results)

# ==========================================================
# Evaluate AfroXLM-R on Test Set
# ==========================================================

import numpy as np
from sklearn.metrics import classification_report, accuracy_score, precision_score, recall_score, f1_score

# Run prediction on test dataset
afro_test_results = afro_trainer.predict(test_dataset)

# Get predicted labels
afro_predictions = np.argmax(
    afro_test_results.predictions,
    axis=1
)

# Get true labels
afro_true_labels = afro_test_results.label_ids


# Calculate evaluation metrics
accuracy = accuracy_score(
    afro_true_labels,
    afro_predictions
)

precision = precision_score(
    afro_true_labels,
    afro_predictions,
    average="weighted"
)

recall = recall_score(
    afro_true_labels,
    afro_predictions,
    average="weighted"
)

f1 = f1_score(
    afro_true_labels,
    afro_predictions,
    average="weighted"
)


print("===== AfroXLM-R Test Results =====")
print(f"Accuracy : {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall   : {recall:.4f}")
print(f"F1-score : {f1:.4f}")


# Classification report
print("\n===== Classification Report =====")
print(
    classification_report(
        afro_true_labels,
        afro_predictions
    )
)


# Check prediction size
print("\nNumber of test samples:")
print("True labels :", len(afro_true_labels))
print("Predictions :", len(afro_predictions))

# ==========================================================
# Save AfroXLM-R Real Performance
# ==========================================================

afro_accuracy = accuracy
afro_precision = precision
afro_recall = recall
afro_f1 = f1

print(afro_accuracy, afro_f1)

# ==========================================================
# Plot AfroXLM-R Confusion Matrix
# ==========================================================

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix

# Create confusion matrix
cm = confusion_matrix(
    afro_true_labels,
    afro_predictions
)

# Your 9 intention class names
labels = [
    "Assertion",
    "Complaint",
    "Phatic",
    "Promise",
    "Request",
    "Question",
    "Threat",
    "Warning",
    "Suggestion"
]

# Plot
plt.figure(figsize=(12,10))

sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    xticklabels=labels,
    yticklabels=labels,
    cmap="Blues"
)

plt.xlabel("Predicted Intention")
plt.ylabel("Actual Intention")
plt.title("Confusion Matrix of AfroXLM-R")

plt.xticks(rotation=45)
plt.yticks(rotation=0)

plt.tight_layout()

plt.show()

# ==========================================================
# Plot Classification Report of AfroXLM-R
# ==========================================================

import matplotlib.pyplot as plt
from sklearn.metrics import classification_report
import pandas as pd

# Class names
labels = [
    "Assertion",
    "Complaint",
    "Phatic",
    "Promise",
    "Request",
    "Question",
    "Threat",
    "Warning",
    "Suggestion"
]

# Generate classification report
report = classification_report(
    afro_true_labels,
    afro_predictions,
    target_names=labels,
    output_dict=True
)

# Convert to DataFrame
report_df = pd.DataFrame(report).transpose()

# Remove accuracy, macro avg, weighted avg for class comparison
class_report = report_df.iloc[:len(labels)]

# Plot Precision, Recall, F1-score
class_report[['precision', 'recall', 'f1-score']].plot(
    kind='bar',
    figsize=(12,6)
)

plt.title("AfroXLM-R Classification Report")
plt.xlabel("Intention Classes")
plt.ylabel("Score")

plt.ylim(0,1)

plt.xticks(
    rotation=45,
    ha='right'
)

plt.legend(
    loc='lower right'
)

plt.tight_layout()

plt.show()

# ==========================================================
# AfroXLM-R Error Analysis (Real Misclassified Samples)
# ==========================================================

import pandas as pd
import numpy as np


# Get original test texts
test_texts = test_dataset["text"]


# Your class names
labels = [
    "Assertion",
    "Complaint",
    "Phatic",
    "Promise",
    "Request",
    "Question",
    "Threat",
    "Warning",
    "Suggestion"
]


# Create error analysis dataframe
error_analysis = pd.DataFrame({
    "Text": test_texts,
    "True_Label": [
        labels[i] for i in afro_true_labels
    ],
    "Predicted_Label": [
        labels[i] for i in afro_predictions
    ]
})


# Select only incorrect predictions
errors = error_analysis[
    error_analysis["True_Label"] != error_analysis["Predicted_Label"]
]


# Display errors
print("Total test samples:", len(error_analysis))
print("Total errors:", len(errors))

errors.head(20)

# ==========================================================
# Plot Real AfroXLM-R Training Accuracy Curve
# ==========================================================

import matplotlib.pyplot as plt


# Get training history from HuggingFace Trainer
history = afro_trainer.state.log_history


# Extract epochs and evaluation accuracy
epochs = []
train_loss = []
eval_accuracy = []

for record in history:
    if "eval_accuracy" in record:
        epochs.append(record["epoch"])
        eval_accuracy.append(record["eval_accuracy"])


# Plot accuracy curve
plt.figure(figsize=(8,5))

plt.plot(
    epochs,
    eval_accuracy,
    marker="o"
)

plt.xlabel("Epoch")
plt.ylabel("Accuracy")

plt.title("AfroXLM-R Validation Accuracy During Training")

plt.ylim(0,1)

plt.grid(True)

plt.xticks(epochs)

plt.show()

# ==========================================================
# Real Training Loss and Validation Loss Curve
# ==========================================================

import matplotlib.pyplot as plt


history = afro_trainer.state.log_history

train_epochs = []
train_losses = []

eval_epochs = []
eval_losses = []


for record in history:
    if "loss" in record and "epoch" in record:
        train_epochs.append(record["epoch"])
        train_losses.append(record["loss"])

    if "eval_loss" in record:
        eval_epochs.append(record["epoch"])
        eval_losses.append(record["eval_loss"])


plt.figure(figsize=(8,5))

plt.plot(
    train_epochs,
    train_losses,
    marker="o",
    label="Training Loss"
)

plt.plot(
    eval_epochs,
    eval_losses,
    marker="o",
    label="Validation Loss"
)

plt.xlabel("Epoch")
plt.ylabel("Loss")

plt.title("AfroXLM-R Training and Validation Loss")

plt.legend()

plt.grid(True)

plt.show()

# ==========================================================
# Real AfroXLM-R F1-score per Intention Class
# ==========================================================

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import classification_report


# Your actual class names
class_names = [
    "Assertion",
    "Complaint",
    "Phatic",
    "Promise",
    "Request",
    "Question",
    "Threat",
    "Warning",
    "Suggestion"
]


# Generate real classification report
report = classification_report(
    afro_true_labels,
    afro_predictions,
    target_names=class_names,
    output_dict=True
)


# Convert to dataframe
report_df = pd.DataFrame(report).transpose()


# Select only intention classes
f1_values = report_df.loc[
    class_names,
    "f1-score"
]


# Plot F1-score
plt.figure(figsize=(10,5))

f1_values.plot(
    kind="bar"
)

plt.xlabel("Intention Classes")
plt.ylabel("F1-score")

plt.title("AfroXLM-R F1-score per Intention Class")

plt.ylim(0,1)

plt.xticks(
    rotation=45,
    ha="right"
)

plt.grid(axis="y")

plt.tight_layout()

plt.show()

# ==========================================================
# Real Intention Class Distribution
# ==========================================================

import matplotlib.pyplot as plt

class_counts = train_dataset.to_pandas()["labels"].value_counts()

plt.figure(figsize=(10,5))

class_counts.sort_index().plot(
    kind="bar"
)

plt.xlabel("Intention Classes")
plt.ylabel("Number of Samples")

plt.title("Distribution of Amharic Intention Classes")

plt.xticks(rotation=45)

plt.grid(axis="y")

plt.tight_layout()

plt.show()

# ==========================================================
# AfroXLM-R Prediction on New Amharic Sentences
# ==========================================================

import torch
import pandas as pd


# 15 Amharic test sentences
sentences = [
    "እባክህ ይህን ስራ እንድትረዳኝ እጠይቃለሁ።",
    "ዛሬ በጣም ደስ ብሎኛል።",
    "ይህ አገልግሎት በጣም መጥፎ ነው።",
    "ነገ ስራውን እጨርሳለሁ።",
    "እንዴት ነህ?",
    "እባክዎ መረጃውን ላኩልኝ።",
    "ይህን ካደረግህ ችግር ይፈጠራል።",
    "እኔ እስማማለሁ።",
    "ለምን ይህን አደረግህ?",
    "እንኳን ደህና መጣህ።",
    "ስለ እርዳታህ አመሰግናለሁ።",
    "ይህ ምርት ጥራት የለውም።",
    "እባክህ በፍጥነት መልስ ስጠኝ።",
    "እኔ ወደ ትምህርት ቤት እሄዳለሁ።",
    "ይህን ሀሳብ እደግፋለሁ።"
]


# Your class labels (must match training label mapping)
labels = [
    "Assertion",
    "Complaint",
    "Phatic",
    "Promise",
    "Request",
    "Question",
    "Threat",
    "Warning",
    "Suggestion"
]


# Prediction function
def predict_intention(text):

    inputs = afro_tokenizer(
        text,
        return_tensors="pt",
        truncation=True,
        padding=True
    )

    inputs = {
        k: v.to(afro_trainer.model.device)
        for k, v in inputs.items()
    }

    with torch.no_grad():
        outputs = afro_trainer.model(**inputs)

    prediction = torch.argmax(
        outputs.logits,
        dim=1
    ).item()

    confidence = torch.softmax(
        outputs.logits,
        dim=1
    )[0][prediction].item()

    return labels[prediction], confidence


# Run prediction
results = []

for sentence in sentences:
    intention, confidence = predict_intention(sentence)

    results.append([
        sentence,
        intention,
        round(confidence,4)
    ])


# Display results
prediction_df = pd.DataFrame(
    results,
    columns=[
        "Amharic Sentence",
        "Predicted Intention",
        "Confidence"
    ]
)

prediction_df

# ==========================================================
# Cell 13: Test Prediction on New Amharic Sentences
# ==========================================================

import torch
import pandas as pd


print("="*60)
print("Testing AfroXLM-R on New Amharic Sentences")
print("="*60)


# ==========================================================
# Label mapping (MUST match your training label order)
# ==========================================================

label_names = [
    "Request",
    "Assertion",
    "Question",
    "Suggestion",
    "Warning",
    "Sarcasm/Irony",
    "Complaint",
    "Phatic",
    "Promise"
]


# ==========================================================
# New Amharic test sentences
# ==========================================================

test_sentences = [
    "እባክህ ይህን መረጃ ላክልኝ።",
    "ይህ አገልግሎት በጣም መጥፎ ነው።",
    "ነገ ስራውን እጨርሳለሁ።",
    "እንዴት ነህ?",
    "ለምን ይህን ውሳኔ ወሰንክ?",
    "እኔ ይህን ሀሳብ እደግፋለሁ።",
    "ይህን ካደረግህ ችግር ይፈጠራል።",
    "እባክዎ ህጉን ይከተሉ።",
    "ይህ ሀሳብ ችግሩን ለመፍታት ይረዳል።",
    "ዛሬ በጣም ደስ ብሎኛል።"
]


results = []


# ==========================================================
# Prediction
# ==========================================================

for sentence in test_sentences:

    inputs = afro_tokenizer(
        sentence,
        return_tensors="pt",
        truncation=True,
        padding=True
    )


    # Move input to GPU/CPU
    inputs = {
        key: value.to(afro_trainer.model.device)
        for key, value in inputs.items()
    }


    with torch.no_grad():

        outputs = afro_trainer.model(**inputs)


    # Predicted class
    prediction_id = torch.argmax(
        outputs.logits,
        dim=1
    ).item()


    predicted_label = label_names[prediction_id]


    # Confidence
    confidence = torch.softmax(
        outputs.logits,
        dim=1
    )[0][prediction_id].item()


    results.append(
        [
            sentence,
            predicted_label,
            confidence
        ]
    )


# ==========================================================
# Display Results
# ==========================================================

prediction_df = pd.DataFrame(
    results,
    columns=[
        "Amharic Sentence",
        "Predicted Intention",
        "Confidence"
    ]
)


print("\nPrediction Results")
print("-"*60)

prediction_df

afro_trainer.save_model("./AfroXLMR_Amharic_Intention_Model")
afro_tokenizer.save_pretrained("./AfroXLMR_Amharic_Intention_Model")

print("AfroXLM-R model saved successfully.")

#mBERT for Amharic Intention Detection    Load mBERT Tokenizer
# ==========================================================
# mBERT Tokenizer
# ==========================================================

from transformers import AutoTokenizer

mbert_model_name = "bert-base-multilingual-cased"

mbert_tokenizer = AutoTokenizer.from_pretrained(
    mbert_model_name
)

print("mBERT tokenizer loaded successfully.")

# ==========================================================
# Reload Dataset for mBERT
# ==========================================================

import pandas as pd
from datasets import Dataset

# Change this to your uploaded CSV filename
df = pd.read_csv("amharic_intention_dataset.csv")

print(df.columns)
print(df.head())

# ==========================================================
# Create mBERT Train / Validation / Test Dataset
# ==========================================================

from datasets import Dataset

train_df = df[df["split"] == "train"]
val_df   = df[df["split"] == "val"]
test_df  = df[df["split"] == "test"]


mbert_train_dataset = Dataset.from_pandas(
    train_df,
    preserve_index=False
)

mbert_val_dataset = Dataset.from_pandas(
    val_df,
    preserve_index=False
)

mbert_test_dataset = Dataset.from_pandas(
    test_df,
    preserve_index=False
)


print(mbert_train_dataset.column_names)
print(mbert_train_dataset[0])

# ==========================================================
# mBERT Tokenization
# ==========================================================

def mbert_tokenize(batch):

    tokens = mbert_tokenizer(
        batch["text"],
        truncation=True,
        max_length=128
    )

    # Use label_id as target
    tokens["labels"] = batch["label_id"]

    return tokens


mbert_train_dataset = mbert_train_dataset.map(
    mbert_tokenize,
    batched=True
)

mbert_val_dataset = mbert_val_dataset.map(
    mbert_tokenize,
    batched=True
)

mbert_test_dataset = mbert_test_dataset.map(
    mbert_tokenize,
    batched=True
)

# ==========================================================
# Clean mBERT Dataset Columns
# ==========================================================

columns_to_remove = [
    "id",
    "text",
    "label",
    "label_id",
    "template_id",
    "split"
]


mbert_train_dataset = mbert_train_dataset.remove_columns(
    columns_to_remove
)

mbert_val_dataset = mbert_val_dataset.remove_columns(
    columns_to_remove
)

mbert_test_dataset = mbert_test_dataset.remove_columns(
    columns_to_remove
)


print(mbert_train_dataset.column_names)
print(mbert_train_dataset[0])

# ==========================================================
# Load mBERT Classification Model
# ==========================================================

from transformers import AutoModelForSequenceClassification

num_labels = 9

mbert_model = AutoModelForSequenceClassification.from_pretrained(
    "bert-base-multilingual-cased",
    num_labels=num_labels
)

mbert_model.to("cuda")

print("mBERT model loaded successfully.")

# ==========================================================
# mBERT Data Collator
# ==========================================================

from transformers import DataCollatorWithPadding

mbert_data_collator = DataCollatorWithPadding(
    tokenizer=mbert_tokenizer
)

print("mBERT Data Collator Ready")

# ==========================================================
# mBERT Trainer
# ==========================================================

from transformers import Trainer

mbert_trainer = Trainer(

    model=mbert_model,

    args=training_args,

    train_dataset=mbert_train_dataset,

    eval_dataset=mbert_val_dataset,

    processing_class=mbert_tokenizer,

    data_collator=mbert_data_collator,

    compute_metrics=compute_metrics
)

print("mBERT Trainer created successfully")

# ==========================================================
# mBERT Training
# ==========================================================

import time

print("="*60)
print("mBERT Training Started...")
print("="*60)

start_time = time.time()

mbert_trainer.train()

mbert_training_time = (time.time() - start_time) / 60

print("="*60)
print(
    "Training Time:",
    round(mbert_training_time, 2),
    "minutes"
)

# ==========================================================
# mBERT Test Evaluation
# ==========================================================

import numpy as np
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

predictions = mbert_trainer.predict(
    mbert_test_dataset
)

y_true = predictions.label_ids

y_pred = np.argmax(
    predictions.predictions,
    axis=1
)

accuracy = accuracy_score(
    y_true,
    y_pred
)

precision = precision_score(
    y_true,
    y_pred,
    average="weighted",
    zero_division=0
)

recall = recall_score(
    y_true,
    y_pred,
    average="weighted",
    zero_division=0
)

f1 = f1_score(
    y_true,
    y_pred,
    average="weighted",
    zero_division=0
)


print("="*60)
print("mBERT Test Results")
print("="*60)

print(f"Accuracy : {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall   : {recall:.4f}")
print(f"F1-score : {f1:.4f}")
print("="*60)

# ==========================================================
# Save mBERT Real Performance
# ==========================================================

mbert_accuracy = accuracy
mbert_precision = precision
mbert_recall = recall
mbert_f1 = f1

print(mbert_accuracy, mbert_f1)

# ==========================================================
# BiLSTM Imports
# ==========================================================

import pandas as pd
import numpy as np
import torch
import torch.nn as nn

from torch.utils.data import Dataset, DataLoader

from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

from collections import Counter
from torch.nn.utils.rnn import pad_sequence

print("BiLSTM environment ready")

# ==========================================================
# Load Dataset
# ==========================================================

df = pd.read_csv(
    "amharic_intention_dataset.csv"
)

print(df.head())

print(df.columns)

# ==========================================================
# Dataset Split
# ==========================================================

train_df = df[df["split"]=="train"]

val_df = df[df["split"]=="val"]

test_df = df[df["split"]=="test"]


print(
    len(train_df),
    len(val_df),
    len(test_df)
)

# ==========================================================
# Build Vocabulary
# ==========================================================

def tokenize(text):
    return text.split()


counter = Counter()

for text in train_df["text"]:
    counter.update(tokenize(text))


vocab = {
    word:index+2
    for index,word in enumerate(counter)
}


vocab["<PAD>"] = 0
vocab["<UNK>"] = 1


vocab_size = len(vocab)


print("Vocabulary size:", vocab_size)

# ==========================================================
# Text Encoding
# ==========================================================

def encode_text(text):

    tokens = tokenize(text)

    return [
        vocab.get(word, vocab["<UNK>"])
        for word in tokens
    ]


train_sequences = [
    encode_text(x)
    for x in train_df["text"]
]


val_sequences = [
    encode_text(x)
    for x in val_df["text"]
]


test_sequences = [
    encode_text(x)
    for x in test_df["text"]
]

# ==========================================================
# Dataset Class
# ==========================================================

class AmharicDataset(Dataset):

    def __init__(self, sequences, labels):

        self.sequences = sequences
        self.labels = labels


    def __len__(self):

        return len(self.labels)


    def __getitem__(self, idx):

        return (
            torch.tensor(
                self.sequences[idx],
                dtype=torch.long
            ),
            torch.tensor(
                self.labels[idx],
                dtype=torch.long
            )
        )

# ==========================================================
# DataLoader
# ==========================================================

def collate(batch):

    sequences, labels = zip(*batch)

    sequences = pad_sequence(
        sequences,
        batch_first=True,
        padding_value=0
    )

    labels = torch.tensor(labels)

    return sequences, labels


train_dataset = AmharicDataset(
    train_sequences,
    train_df["label_id"].values
)

val_dataset = AmharicDataset(
    val_sequences,
    val_df["label_id"].values
)

test_dataset = AmharicDataset(
    test_sequences,
    test_df["label_id"].values
)


train_loader = DataLoader(
    train_dataset,
    batch_size=32,
    shuffle=True,
    collate_fn=collate
)


val_loader = DataLoader(
    val_dataset,
    batch_size=32,
    collate_fn=collate
)


test_loader = DataLoader(
    test_dataset,
    batch_size=32,
    collate_fn=collate
)

# ==========================================================
# BiLSTM Model
# ==========================================================

class BiLSTMClassifier(nn.Module):

    def __init__(
        self,
        vocab_size,
        embedding_dim,
        hidden_dim,
        num_classes
    ):

        super().__init__()

        self.embedding = nn.Embedding(
            vocab_size,
            embedding_dim,
            padding_idx=0
        )

        self.lstm = nn.LSTM(
            embedding_dim,
            hidden_dim,
            batch_first=True,
            bidirectional=True
        )

        self.fc = nn.Linear(
            hidden_dim*2,
            num_classes
        )


    def forward(self,x):

        x = self.embedding(x)

        _,(hidden,_) = self.lstm(x)

        hidden = torch.cat(
            (hidden[-2], hidden[-1]),
            dim=1
        )

        output = self.fc(hidden)

        return output

device = torch.device(
    "cuda" if torch.cuda.is_available()
    else "cpu"
)


model = BiLSTMClassifier(
    vocab_size=vocab_size,
    embedding_dim=128,
    hidden_dim=128,
    num_classes=9
)


model.to(device)

print("BiLSTM model ready")

# ==========================================================
# BiLSTM Training
# ==========================================================

import time

criterion = nn.CrossEntropyLoss()

optimizer = torch.optim.Adam(
    model.parameters(),
    lr=0.001
)


epochs = 10

train_losses = []
val_losses = []
val_accuracies = []


start_time = time.time()


for epoch in range(epochs):

    model.train()

    total_loss = 0


    for batch_x, batch_y in train_loader:

        batch_x = batch_x.to(device)
        batch_y = batch_y.to(device)


        optimizer.zero_grad()


        outputs = model(batch_x)


        loss = criterion(
            outputs,
            batch_y
        )


        loss.backward()

        optimizer.step()


        total_loss += loss.item()


    train_loss = total_loss / len(train_loader)


    # Validation
    model.eval()

    val_loss = 0
    predictions = []
    true_labels = []


    with torch.no_grad():

        for batch_x, batch_y in val_loader:

            batch_x = batch_x.to(device)
            batch_y = batch_y.to(device)


            outputs = model(batch_x)


            loss = criterion(
                outputs,
                batch_y
            )


            val_loss += loss.item()


            preds = torch.argmax(
                outputs,
                dim=1
            )


            predictions.extend(
                preds.cpu().numpy()
            )

            true_labels.extend(
                batch_y.cpu().numpy()
            )


    val_loss = val_loss / len(val_loader)


    accuracy = accuracy_score(
        true_labels,
        predictions
    )


    train_losses.append(train_loss)
    val_losses.append(val_loss)
    val_accuracies.append(accuracy)


    print(
        f"Epoch {epoch+1}/{epochs}"
    )

    print(
        f"Train Loss: {train_loss:.4f}"
    )

    print(
        f"Val Loss: {val_loss:.4f}"
    )

    print(
        f"Val Accuracy: {accuracy:.4f}"
    )

    print("-"*50)



training_time = (time.time()-start_time)/60


print("="*60)
print(
    "Training Time:",
    round(training_time,2),
    "minutes"
)
print("="*60)

# ==========================================================
# BiLSTM Test Evaluation
# ==========================================================

model.eval()

test_predictions = []
test_labels = []


with torch.no_grad():

    for batch_x, batch_y in test_loader:

        batch_x = batch_x.to(device)
        batch_y = batch_y.to(device)


        outputs = model(batch_x)


        preds = torch.argmax(
            outputs,
            dim=1
        )


        test_predictions.extend(
            preds.cpu().numpy()
        )

        test_labels.extend(
            batch_y.cpu().numpy()
        )


accuracy = accuracy_score(
    test_labels,
    test_predictions
)


precision = precision_score(
    test_labels,
    test_predictions,
    average="weighted",
    zero_division=0
)


recall = recall_score(
    test_labels,
    test_predictions,
    average="weighted",
    zero_division=0
)


f1 = f1_score(
    test_labels,
    test_predictions,
    average="weighted",
    zero_division=0
)


print("="*60)
print("BiLSTM Test Results")
print("="*60)

print(f"Accuracy : {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall   : {recall:.4f}")
print(f"F1-score : {f1:.4f}")
print("="*60)

# Save real BiLSTM results

bilstm_accuracy = accuracy
bilstm_precision = precision
bilstm_recall = recall
bilstm_f1 = f1

print(bilstm_accuracy, bilstm_f1)

# Save BiLSTM real performance

bilstm_accuracy = accuracy
bilstm_precision = precision
bilstm_recall = recall
bilstm_f1 = f1

# ==========================================================
# BiLSTM Confusion Matrix
# ==========================================================

import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay


cm = confusion_matrix(
    test_labels,
    test_predictions
)


label_names = [
    "Request",
    "Assertion",
    "Question",
    "Suggestion",
    "Warning",
    "Sarcasm/Irony",
    "Complaint",
    "Phatic",
    "Promise"
]


plt.figure(figsize=(10,8))


disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=label_names
)


disp.plot(
    xticks_rotation=45
)


plt.title(
    "BiLSTM Confusion Matrix for Amharic Intention Detection"
)


plt.show()

# ==========================================================
# BiLSTM Learning Curves
# ==========================================================

import matplotlib.pyplot as plt


epochs_range = range(1, epochs+1)


# Loss curve
plt.figure(figsize=(8,5))

plt.plot(
    epochs_range,
    train_losses,
    label="Training Loss"
)

plt.plot(
    epochs_range,
    val_losses,
    label="Validation Loss"
)

plt.xlabel("Epoch")
plt.ylabel("Loss")

plt.title(
    "BiLSTM Training and Validation Loss"
)

plt.legend()

plt.grid(True)

plt.show()



# Accuracy curve

plt.figure(figsize=(8,5))

plt.plot(
    epochs_range,
    val_accuracies,
    marker="o"
)

plt.xlabel("Epoch")

plt.ylabel("Validation Accuracy")

plt.title(
    "BiLSTM Validation Accuracy"
)

plt.grid(True)

plt.show()

# ==========================================================
# TF-IDF + SVM Imports
# ==========================================================

import pandas as pd
import time

from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.svm import LinearSVC

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report
)

print("TF-IDF + SVM environment ready")

# ==========================================================
# Load Dataset
# ==========================================================

df = pd.read_csv(
    "amharic_intention_dataset.csv"
)


train_df = df[df["split"]=="train"]

val_df = df[df["split"]=="val"]

test_df = df[df["split"]=="test"]


print(train_df.shape)
print(val_df.shape)
print(test_df.shape)

# ==========================================================
# Prepare Data
# ==========================================================

X_train = train_df["text"]

y_train = train_df["label_id"]


X_val = val_df["text"]

y_val = val_df["label_id"]


X_test = test_df["text"]

y_test = test_df["label_id"]


print("Data prepared")

# ==========================================================
# TF-IDF Vectorizer
# ==========================================================

tfidf = TfidfVectorizer(
    analyzer="word",
    ngram_range=(1,2),
    max_features=10000
)


X_train_tfidf = tfidf.fit_transform(
    X_train
)


X_val_tfidf = tfidf.transform(
    X_val
)


X_test_tfidf = tfidf.transform(
    X_test
)


print(
    "TF-IDF feature size:",
    X_train_tfidf.shape
)

# ==========================================================
# Linear SVM Training
# ==========================================================

start_time = time.time()


svm_model = LinearSVC()


svm_model.fit(
    X_train_tfidf,
    y_train
)


training_time = (
    time.time()-start_time
)/60


print(
    "Training Time:",
    round(training_time,2),
    "minutes"
)

# ==========================================================
# TF-IDF + SVM Evaluation
# ==========================================================

svm_predictions = svm_model.predict(
    X_test_tfidf
)


accuracy = accuracy_score(
    y_test,
    svm_predictions
)


precision = precision_score(
    y_test,
    svm_predictions,
    average="weighted",
    zero_division=0
)


recall = recall_score(
    y_test,
    svm_predictions,
    average="weighted",
    zero_division=0
)


f1 = f1_score(
    y_test,
    svm_predictions,
    average="weighted",
    zero_division=0
)


print("="*60)
print("TF-IDF + SVM Test Results")
print("="*60)

print(f"Accuracy : {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall   : {recall:.4f}")
print(f"F1-score : {f1:.4f}")

print("="*60)

print(svm_accuracy, svm_f1)

# Save TF-IDF + SVM real metrics

svm_accuracy = accuracy_score(y_test, svm_predictions)

svm_precision = precision_score(
    y_test,
    svm_predictions,
    average="weighted",
    zero_division=0
)

svm_recall = recall_score(
    y_test,
    svm_predictions,
    average="weighted",
    zero_division=0
)

svm_f1 = f1_score(
    y_test,
    svm_predictions,
    average="weighted",
    zero_division=0
)

# ==========================================================
# Model Performance Comparison Graph (Real Values)
# ==========================================================

import matplotlib.pyplot as plt
import pandas as pd


results = pd.DataFrame({

    "Model":[
        "AfroXLM-R",
        "XLM-RoBERTa",
        "TF-IDF + SVM",
        "BiLSTM",
        "mBERT"
    ],

    "Accuracy":[
        afro_accuracy,
        xlmr_accuracy,
        svm_accuracy,
        bilstm_accuracy,
        mbert_accuracy
    ],

    "F1-score":[
        afro_f1,
        xlmr_f1,
        svm_f1,
        bilstm_f1,
        mbert_f1
    ]
})


print(results)


# Plot
plt.figure(figsize=(10,5))

x = range(len(results))

plt.bar(
    x,
    results["Accuracy"],
    width=0.4,
    label="Accuracy"
)

plt.bar(
    [i+0.4 for i in x],
    results["F1-score"],
    width=0.4,
    label="F1-score"
)


plt.xticks(
    [i+0.2 for i in x],
    results["Model"],
    rotation=45
)


plt.ylabel("Score")

plt.ylim(0,1)

plt.title(
    "Performance Comparison of Models for Amharic Intention Detection"
)

plt.legend()

plt.grid(axis="y")

plt.tight_layout()

plt.show()

print("AfroXLM-R:", afro_accuracy, afro_f1)
print("XLM-RoBERTa:", xlmr_accuracy, xlmr_f1)
print("SVM:", svm_accuracy, svm_f1)
print("BiLSTM:", bilstm_accuracy, bilstm_f1)
print("mBERT:", mbert_accuracy, mbert_f1)

# ==========================================================
# Dataset Label Distribution
# ==========================================================

import matplotlib.pyplot as plt
import pandas as pd

# Load dataset
df = pd.read_csv("amharic_intention_dataset.csv")

# Count samples per class
label_counts = df["label"].value_counts().sort_index()

# Plot
plt.figure(figsize=(10,6))

plt.bar(label_counts.index, label_counts.values)

plt.xlabel("Intention Class", fontsize=12)
plt.ylabel("Number of Samples", fontsize=12)
plt.title("Distribution of Intention Classes in the Amharic Intention Dataset", fontsize=14)

plt.xticks(rotation=45, ha="right")
plt.grid(axis="y", linestyle="--", alpha=0.6)

plt.tight_layout()

# Save publication-quality figure
plt.savefig(
    "Dataset_Label_Distribution.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

# ==========================================================
# Dataset Label Distribution (Ordered by label_id)
# ==========================================================

import matplotlib.pyplot as plt
import pandas as pd

df = pd.read_csv("amharic_intention_dataset.csv")

label_order = (
    df[["label_id", "label"]]
    .drop_duplicates()
    .sort_values("label_id")
)

counts = (
    df.groupby(["label_id", "label"])
      .size()
      .reset_index(name="Count")
      .sort_values("label_id")
)

plt.figure(figsize=(10,6))

plt.bar(counts["label"], counts["Count"])

plt.xlabel("Intention Class", fontsize=12)
plt.ylabel("Number of Samples", fontsize=12)
plt.title("Distribution of Intention Classes in the Amharic Intention Dataset", fontsize=14)

plt.xticks(rotation=45, ha="right")
plt.grid(axis="y", linestyle="--", alpha=0.6)

plt.tight_layout()

plt.savefig(
    "Dataset_Label_Distribution.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

# ==========================================================
# Store Real Test Results of All Models
# ==========================================================

import pandas as pd


results = pd.DataFrame({

    "Model": [
        "TF-IDF + SVM",
        "BiLSTM",
        "mBERT",
        "XLM-RoBERTa",
        "AfroXLM-R"
    ],

    "Accuracy": [
        svm_accuracy,
        bilstm_accuracy,
        mbert_accuracy,
        xlmr_accuracy,
        afro_accuracy
    ],

    "Precision": [
        svm_precision,
        bilstm_precision,
        mbert_precision,
        xlmr_precision,
        afro_precision
    ],

    "Recall": [
        svm_recall,
        bilstm_recall,
        mbert_recall,
        xlmr_recall,
        afro_recall
    ],

    "F1-score": [
        svm_f1,
        bilstm_f1,
        mbert_f1,
        xlmr_f1,
        afro_f1
    ]
})


print(results)

#performance
import pandas as pd

model_results = pd.DataFrame({
    "Model": [
        "TF-IDF + SVM",
        "BiLSTM",
        "mBERT",
        "XLM-RoBERTa",
        "AfroXLM-R"
    ],

    "Accuracy": [
        svm_accuracy,
        bilstm_accuracy,
        mbert_accuracy,
        xlmr_accuracy,
        afro_accuracy
    ],

    "Precision": [
        svm_precision,
        bilstm_precision,
        mbert_precision,
        xlmr_precision,
        afro_precision
    ],

    "Recall": [
        svm_recall,
        bilstm_recall,
        mbert_recall,
        xlmr_recall,
        afro_recall
    ],

    "F1-score": [
        svm_f1,
        bilstm_f1,
        mbert_f1,
        xlmr_f1,
        afro_f1
    ]
})


model_results

import pandas as pd

results = pd.DataFrame({

    "Model": [
        "TF-IDF + SVM",
        "BiLSTM",
        "mBERT",
        "XLM-RoBERTa",
        "AfroXLM-R"
    ],

    "Accuracy": [
        svm_accuracy,
        bilstm_accuracy,
        mbert_accuracy,
        xlmr_accuracy,
        afro_accuracy
    ],

    "Precision": [
        svm_precision,
        bilstm_precision,
        mbert_precision,
        xlmr_precision,
        afro_precision
    ],

    "Recall": [
        svm_recall,
        bilstm_recall,
        mbert_recall,
        xlmr_recall,
        afro_recall
    ],

    "F1-score": [
        svm_f1,
        bilstm_f1,
        mbert_f1,
        xlmr_f1,
        afro_f1
    ]
})


print(results)

# ==========================================================
# Overall Model Performance Comparison Bar Chart
# ==========================================================

import matplotlib.pyplot as plt
import numpy as np


# Data
models = results["Model"]

accuracy = results["Accuracy"]
precision = results["Precision"]
recall = results["Recall"]
f1 = results["F1-score"]


# Position
x = np.arange(len(models))
width = 0.2


plt.figure(figsize=(12,6))


plt.bar(
    x - 1.5*width,
    accuracy,
    width,
    label="Accuracy"
)

plt.bar(
    x - 0.5*width,
    precision,
    width,
    label="Precision"
)

plt.bar(
    x + 0.5*width,
    recall,
    width,
    label="Recall"
)

plt.bar(
    x + 1.5*width,
    f1,
    width,
    label="F1-score"
)


# Labels
plt.xticks(
    x,
    models,
    rotation=45,
    ha="right"
)

plt.ylabel("Score")

plt.xlabel("Models")

plt.ylim(0,1)


plt.title(
    "Performance Comparison of Models for Amharic Intention Detection"
)


plt.legend()

plt.grid(
    axis="y"
)


plt.tight_layout()


# Display
plt.show()

# Install package
!pip install statsmodels

# ==========================================================
# Upload Amharic Intention Dataset
# ==========================================================

from google.colab import files
import pandas as pd

uploaded = files.upload()

file_name = list(uploaded.keys())[0]

df = pd.read_csv(file_name)

print("Dataset shape:", df.shape)

df.head()

import pandas as pd
import numpy as np
from statsmodels.stats.inter_rater import fleiss_kappa

# Load annotation files
ann1 = pd.read_csv("annotator1.csv")
ann2 = pd.read_csv("annotator2.csv")
ann3 = pd.read_csv("annotator3.csv")

# Merge on sentence ID
df = ann1[['id', 'label_id']].rename(columns={'label_id':'ann1'})
df = df.merge(
    ann2[['id', 'label_id']].rename(columns={'label_id':'ann2'}),
    on='id'
)
df = df.merge(
    ann3[['id', 'label_id']].rename(columns={'label_id':'ann3'}),
    on='id'
)

print(df.head())

# Number of classes
num_classes = 9

# Build Fleiss' Kappa table
table = np.zeros((len(df), num_classes), dtype=int)

for i, row in enumerate(df[['ann1', 'ann2', 'ann3']].values):
    for label in row:
        table[i, int(label)] += 1

# Calculate Fleiss' Kappa
kappa = fleiss_kappa(table)

print("="*50)
print("Fleiss' Kappa =", round(kappa, 4))
print("="*50)

from sklearn.metrics import cohen_kappa_score

print("Annotator 1 vs Annotator 2:",
      round(cohen_kappa_score(df["ann1"], df["ann2"]), 4))

print("Annotator 1 vs Annotator 3:",
      round(cohen_kappa_score(df["ann1"], df["ann3"]), 4))

print("Annotator 2 vs Annotator 3:",
      round(cohen_kappa_score(df["ann2"], df["ann3"]), 4))

import pandas as pd
import numpy as np
from statsmodels.stats.inter_rater import fleiss_kappa

# Read annotation files
ann1 = pd.read_csv("annotator1.csv")
ann2 = pd.read_csv("annotator2.csv")
ann3 = pd.read_csv("annotator3.csv")

# Merge by id
df = ann1[['id','label_id']].rename(columns={'label_id':'ann1'})
df = df.merge(ann2[['id','label_id']].rename(columns={'label_id':'ann2'}), on='id')
df = df.merge(ann3[['id','label_id']].rename(columns={'label_id':'ann3'}), on='id')

num_classes = 9

table = np.zeros((len(df), num_classes), dtype=int)

for i, row in enumerate(df[['ann1','ann2','ann3']].values):
    for label in row:
        table[i, int(label)] += 1

kappa = fleiss_kappa(table)

print("Fleiss' Kappa:", round(kappa, 4))

!pip install scikit-learn statsmodels



from google.colab import files

uploaded = files.upload()

import pandas as pd

ann1 = pd.read_csv("annotator1 (1).csv")
ann2 = pd.read_csv("annotator2 (1).csv")

print("Annotator 1:")
print(ann1.head())

print("\nAnnotator 2:")
print(ann2.head())

print("\nShapes:")
print(ann1.shape, ann2.shape)

print(ann1.columns)
print(ann2.columns)

agreement = pd.DataFrame()

agreement["annotator1"] = ann1["label"]
agreement["annotator2"] = ann2["label"]

agreement.head()

from sklearn.metrics import cohen_kappa_score

kappa = cohen_kappa_score(
    agreement["annotator1"],
    agreement["annotator2"]
)

print("Cohen's Kappa =", round(kappa,4))

print(ann1.columns)
print(ann2.columns)

from sklearn.metrics import cohen_kappa_score

# Calculate Cohen's Kappa
kappa = cohen_kappa_score(
    ann1["label"],
    ann2["label"]
)

print("Cohen's Kappa:", round(kappa,4))

# Show label_id and corresponding label names
mapping = ann1[["label_id", "label"]].drop_duplicates().sort_values("label_id")

print(mapping)

# Percentage agreement

agreement = (ann1["label"] == ann2["label"]).mean()

print("Percentage Agreement:", round(agreement * 100, 2), "%")

disagreement_count = (ann1["label"] != ann2["label"]).sum()

print("Number of disagreements:", disagreement_count)

from statsmodels.stats.inter_rater import fleiss_kappa

# Create Fleiss matrix
n_classes = 9
fleiss_data = []

for i in range(len(ann1)):
    row = [0] * n_classes

    row[int(ann1.loc[i, "label_id"])] += 1
    row[int(ann2.loc[i, "label_id"])] += 1

    fleiss_data.append(row)

fleiss_value = fleiss_kappa(fleiss_data)

print("Fleiss Kappa:", round(fleiss_value,4))

# ==========================================
# Annotation Agreement Analysis
# Two Annotators, 9 Classes
# ==========================================

import pandas as pd
from sklearn.metrics import cohen_kappa_score, confusion_matrix
from statsmodels.stats.inter_rater import fleiss_kappa

# Load files
ann1 = pd.read_csv("annotator1 (1).csv")
ann2 = pd.read_csv("annotator2 (1).csv")

# Extract labels
labels1 = ann1["label_id"]
labels2 = ann2["label_id"]

# ------------------------------------------
# 1. Cohen's Kappa
# ------------------------------------------

cohen = cohen_kappa_score(labels1, labels2)

print("Cohen's Kappa:", round(cohen, 4))


# ------------------------------------------
# 2. Percentage Agreement
# ------------------------------------------

agreement = (labels1 == labels2).mean()

print("Percentage Agreement:", round(agreement*100, 2), "%")


# ------------------------------------------
# 3. Number of disagreements
# ------------------------------------------

disagreements = (labels1 != labels2).sum()

print("Number of disagreements:", disagreements)


# ------------------------------------------
# 4. Fleiss' Kappa
# ------------------------------------------

n_classes = 9

fleiss_matrix = []

for a,b in zip(labels1, labels2):

    row = [0] * n_classes

    row[int(a)] += 1
    row[int(b)] += 1

    fleiss_matrix.append(row)


fleiss = fleiss_kappa(fleiss_matrix)

print("Fleiss Kappa:", round(fleiss,4))


# ------------------------------------------
# 5. Confusion Matrix
# ------------------------------------------

cm = confusion_matrix(
    labels1,
    labels2
)

print("\nConfusion Matrix:")
print(cm)

import pandas as pd

# Count samples per class
label_distribution = ann1.groupby(
    ["label_id", "label"]
).size().reset_index(name="Count")

label_distribution = label_distribution.sort_values("label_id")

print(label_distribution)

split_distribution = ann1.groupby(
    ["split","label"]
).size().reset_index(name="Count")

print(split_distribution)

results = pd.DataFrame({
    "Metric": [
        "Cohen's Kappa",
        "Percentage Agreement",
        "Disagreements"
    ],
    "Value": [
        1.0000,
        "100%",
        0
    ]
})

results.to_csv("annotation_agreement_results.csv", index=False)

print("Saved successfully")

